const NOTIFICATION = [
  {
    id: 1,
    title: "Twitch Rivas League of Legends Showdown",
    img: require("../assets/images/showdown.jpg"),
    date: "1 saat önce",
    notificationType: "EVENT_STARTED_FROM_YOUR_LIST",
    active: true,
  },
  {
    id: 2,
    title: "Twitch Rivals Valorant Turnuvası",
    img: require("../assets/images/valorant-rivals.png"),
    date: "2 saat önce",
    notificationType: "EVENT_STARTED_FROM_YOUR_TEAMS",
    active: true,
  },
  {
    id: 3,
    title: "Twitch Rivals Apex Challenge",
    img: require("../assets/images/apex-rivals.png"),
    date: "9 saat önce",
    notificationType: "EVENT_STARTED_FROM_YOUR_PLAYERS",
    active: false,
  },
  {
    id: 4,
    title: "Twitch Rivas League of Legends Showdown",
    img: require("../assets/images/showdown.jpg"),
    date: "1 gün önce",
    notificationType: "EVENT_STARTED_FROM_YOUR_LIST",
    active: false,
  },
  {
    id: 5,
    title: "Twitch Rivals Valorant Turnuvası",
    img: require("../assets/images/valorant-rivals.png"),
    date: "1 gün önce",
    notificationType: "EVENT_STARTED_FROM_YOUR_LIST",
    active: false,
  },
  {
    id: 6,
    title: "Twitch Rivals Apex Challenge",
    img: require("../assets/images/apex-rivals.png"),
    date: "2 gün önce",
    notificationType: "EVENT_STARTED_FROM_YOUR_LIST",
    active: false,
  },
  {
    id: 7,
    title: "Twitch Rivas League of Legends Showdown",
    img: require("../assets/images/showdown.jpg"),
    date: "1 gün önce",
    notificationType: "EVENT_STARTED_FROM_YOUR_LIST",
    active: false,
  },
  {
    id: 8,
    title: "Twitch Rivals Valorant Turnuvası",
    img: require("../assets/images/valorant-rivals.png"),
    date: "1 gün önce",
    notificationType: "EVENT_STARTED_FROM_YOUR_LIST",
    active: false,
  },
  {
    id: 9,
    title: "Twitch Rivals Apex Challenge",
    img: require("../assets/images/apex-rivals.png"),
    date: "2 gün önce",
    notificationType: "EVENT_STARTED_FROM_YOUR_LIST",
    active: false,
  },
]

export default NOTIFICATION; 